Fix Deprecation Warnings
vehiloco/crypto-checker pull request #41
Opened 2022-03-30 23:31 UTC by al3xliu

2022-04-02 00:49 UTC, wmdietl requested changes
Thanks! Just some small things.

2022-04-02 00:49 UTC, wmdietl commented on src/main/java/org/checkerframework/checker/crypto/CryptoVisitor.java
> +import org.checkerframework.javacutil.*;
Don't do wildcard imports.

2022-04-02 00:49 UTC, wmdietl commented on src/main/java/org/checkerframework/checker/crypto/CryptoVisitor.java
>      final ProcessingEnvironment env;
```suggestion
    protected final ProcessingEnvironment env;
```

2022-04-02 00:49 UTC, wmdietl commented on src/main/java/org/checkerframework/checker/crypto/CryptoVisitor.java
>      final boolean STRONG_BOX_BACKED_ENABLE = checker.getLintOption("strongboxbacked", false);
```suggestion
    protected final boolean STRONG_BOX_BACKED_ENABLE = checker.getLintOption("strongboxbacked", false);
```

2022-04-02 03:35 UTC, al3xliu commented on src/main/java/org/checkerframework/checker/crypto/CryptoVisitor.java
> +import org.checkerframework.javacutil.*;
```suggestion
import org.checkerframework.javacutil.AnnotationUtils;
import org.checkerframework.javacutil.BugInCF;
import org.checkerframework.javacutil.TreeUtils;
import org.checkerframework.javacutil.TypeAnnotationUtils;
import org.checkerframework.javacutil.TypesUtils;
import org.checkerframework.javacutil.AnnotationBuilder;
```

2022-04-02 03:37 UTC, al3xliu commented on src/main/java/org/checkerframework/checker/crypto/CryptoVisitor.java
> +import org.checkerframework.javacutil.*;
Thanks, resolved.

2022-04-03 19:41 UTC, wmdietl approved these changes
Thanks!

2022-04-03 19:41 UTC, merged